export const PACKAGE_NAME = '@threejs-doctor/runtime' as const
export * from './doctor.js'
export * from './quality-controller.js'
export * from './passes/types.js'
export { dprCapPass } from './passes/dpr-cap.js'
export { pixelBudgetPass } from './passes/pixel-budget.js'
export { shadowBudgetPass } from './passes/shadow-budget.js'
export { postfxBudgetPass } from './passes/postfx-budget.js'
export { toneMapLitePass } from './passes/tone-map-lite.js'
export { anisotropyCapPass } from './passes/anisotropy-cap.js'
export { frameloopDemandPass } from './passes/frameloop-demand.js'
export { distanceCullPass } from './passes/distance-cull.js'
export { materialDowngradePass } from './passes/material-downgrade.js'
export { readRendererPixelRatio, readRendererAntialias } from './renderer-read.js'
export { collectHostSceneStats, applyHostInsights, readHostWorldRadius } from './scene-stats.js'
export type { CollectHostSceneOptions, HostSceneInsights, HostSceneCollection } from './scene-stats.js'
export { createGpuFrameSampler, waitGpuMacrotask } from './gpu-timer.js'
export type { GpuFrameSampler, GpuMacrotaskWait } from './gpu-timer.js'
export { isComposerLike, readComposerSize, findComposer } from './composer.js'
export { mountOverlay } from './overlay/mount-overlay.js'
export type { OverlayHandle, MountOverlayOptions } from './overlay/mount-overlay.js'
export { formatQualityHud } from './overlay/format-quality-hud.js'
export type { QualityHudState } from './overlay/format-quality-hud.js'
