export const PACKAGE_NAME = '@threejs-doctor/rules' as const
export * from './types.js'
export * from './profiles.js'
export * from './score.js'
export * from './rule.js'
export { drawCallsRule } from './rules/draw-calls.js'
export { lightsShadowsRule } from './rules/lights-shadows.js'
export { dprRule } from './rules/dpr.js'
export { materialsRule } from './rules/materials.js'
export { texturesRule } from './rules/textures.js'
export { rendererSetupRule } from './rules/renderer-setup.js'
export { lifecycleRule } from './rules/lifecycle.js'
export { transformsRule } from './rules/transforms.js'
export { frameloopRule } from './rules/frameloop.js'
